version: "3"

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    build: ./requirements/mariadb
    volumes:
    - mariadb:/var/lib/mysql
    networks:
    - inception
    env_file: .env
    restart: always
  nginx:
    container_name: nginx
    image: nginx
    build: ./requirements/nginx
    env_file: .env
    volumes:
    - wordpress:/var/www/html
    networks:
    - inception
    depends_on:
    - wordpress
    ports:
    - "443:443"
    restart: always
  wordpress:
    container_name: wordpress
    image: wordpress
    build: ./requirements/wordpress
    env_file: .env
    volumes:
    - wordpress:/var/www/html/
    networks:
    - inception
    depends_on:
    - mariadb
    restart: always
volumes:
  wordpress:
    driver: local
    driver_opts:
        type: none
        o: bind
        device: /home/kohmatsu/data/wordpress
  mariadb:
    driver: local
    driver_opts:
        type: none
        o: bind
        device: /home/kohmatsu/data/mariadb
networks:
  inception:
    driver: bridge